services:
  app:
    container_name: mentora
    #image: m4rkus28/mentora:latest
    build:
      context: .
      dockerfile: Dockerfile
    # Define variable
    environment:
      - WORKERS=4
    ports:
      - "8127:8000"
    env_file:
      - ./.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
