services:
  app:
    container_name: mentora
    #image: m4rkus28/mentora:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
